language: python

branches:
  only:
  - wheels

env:
  global:
    # (1,2) Skip building for Python 2.7 on all platforms
    # (3) reduce build times by skipping Python 3.5 & 3.6 & 3.7
    # (4) skip PyPy for now because of semi-broken images (yum fails)
    - CIBW_SKIP="cp27-* pp27-* cp35-* cp36-* cp37-* pp*"
    # Install dependencies on Linux and OSX
    - CIBW_BEFORE_BUILD="bash -x library_builders.sh"
    # for the openPMD-api build, CMake shall search for
    # static dependencies of HDF5 and ADIOS1 (see setup.py)
    # - CIBW_ENVIRONMENT="HDF5_USE_STATIC_LIBRARIES='ON' ADIOS_USE_STATIC_LIBS='ON'"
    # https://github.com/joerick/cibuildwheel/issues/442#issuecomment-705272500
    # https://github.com/pypa/pip/issues/5735
    - PIP_NO_BUILD_ISOLATION: no

jobs:
  include:
    # perform a linux ARMv8 build
    # blocked by https://github.com/scikit-build/cmake-python-distributions/issues/96
    #            https://github.com/pypa/manylinux/issues/544
    - services: docker
      arch: arm64
      env:
        - CIBW_BUILD="*_aarch64"

    # perform a linux PPC64LE build
    # blocked by https://github.com/pypa/auditwheel/issues/36
    #            https://github.com/pypa/auditwheel/pull/213
    - services: docker
      arch: ppc64le
      env:
       - CIBW_BUILD="*_ppc64le"

    # perform a linux S390X build
    - services: docker
      arch: s390x
      env:
        - CIBW_BUILD="*_s390x"

install:
  # - git clone --branch ${OPENPMD_GIT_REF} --depth 1 https://github.com/openPMD/openPMD-api.git src
  - python3 -m pip install scikit-build
  - python3 -m pip download --no-binary cmake cmake
  - tar -xf cmake-*.tar.gz
  - rm cmake-*.tar.gz
  - mv cmake-* src
  - mv library_builders.sh src/
  - python3 -m pip install cibuildwheel==1.7.1

# build wheel
script:
  - cd src
  - travis_wait 50 python3 -m cibuildwheel --output-dir ../wheelhouse
  - cd ..

#after_success:
#  - if [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
#        python3 -m pip install -U twine;
#        python3 -m twine upload --repository testpypi --skip-existing wheelhouse/*;
#    fi
