name: wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]  # windows-2019

    steps:
#    - uses: actions/checkout@v2
#      with:
#        path: 'src'
#        ref: '0.12.0-alpha'

    - uses: actions/checkout@v2
#      with:
#        path: 'src/.github/'

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Get Sources
      run: |
        python -m pip install scikit-build
        python -m pip download --no-binary cmake cmake
        tar -xf cmake-*.tar.gz
        rm cmake-*.tar.gz
        mv cmake-* src
        mv library_builders.sh src/

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.7.1

    - name: Build wheel
      env:
        # (1,2) Skip building for Python 2.7 on all platforms
        # (3) reduce build times by skipping Python 3.5 & 3.6 & 3.7
        # (4) skip PyPy for now because of semi-broken images (yum fails)
        CIBW_SKIP: cp27-* pp27-* cp35-* cp36-* cp37-* pp*
        # Apple Silicon and universal2 wheels (Pip 20.3+/20.6+)
        CIBW_ARCHS_MACOS: x86_64 arm64 universal2
        # Skip testing on emulated and cross-compiled architectures
        CIBW_TEST_SKIP: '*-macosx_arm64 *-macosx_universal2:arm64 *-manylinux_{aarch64,ppc64le,s390x}'
        # Install dependencies
        CIBW_BEFORE_BUILD_LINUX: bash -x library_builders.sh
        CIBW_BEFORE_BUILD_MACOS: bash -x library_builders.sh
        CIBW_BEFORE_BUILD_WINDOWS: 'cmd /E:ON /V:ON /C library_builders.bat'
        # some environment vars
        # CIBW_ENVIRONMENT: ABC='ON' DEF='OFF'
        # C++11 & 14 support in macOS 10.9+
        # C++17 support in macOS 10.13+/10.14+
        #   https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#macos-and-deployment-target-versions
        # CMake needs 10.10+
        MACOSX_DEPLOYMENT_TARGET: 10.10
        # https://github.com/joerick/cibuildwheel/issues/442#issuecomment-705272500
        # https://github.com/pypa/pip/issues/5735
        PIP_NO_BUILD_ISOLATION: no
      run: |
        cd src
        python -m cibuildwheel --output-dir ../wheelhouse

    - name: Publish on pypi.org
#      if: github.event_name == 'push' && github.repository == 'ax3l/cmake-cibuildwheel' && github.ref == 'refs/heads/wheels'
      if: false  # skip because we are not yet uploading
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypa_gh_action_upload }}
      run: |
        python -m pip install -U twine
        python -m twine upload --repository testpypi --skip-existing wheelhouse/*

    - uses: actions/upload-artifact@v1
      name: Publish as GitHub artifact
      with:
        name: wheels
        path: ./wheelhouse
